#!/bin/bash

cd /home/cron/ip

rm -f index.html
wget myip.dnsdynamic.com

# echo "`date`:"  >>ip
# cat index.html  >>ip

echo "`date`: `cat index.html`" >>ip

git add ip
git commit -s -m "`date`"
git push -u origin test

